### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by shaifugpt** [nesl/sensegen#1]
Hi, I am trying to use your code to generate synthetic data for my dataset. But it gives infinity on first iteration (#0) and nan on second (#1). Can you please tell what can be possible reason for this. Another doubt is that of the input data is multivariate, then why the fake data generated is univariate. Is'nt it is also expected to be multivariate. Thanks.

**Comment by malzantot** [comment]
It is hard to tell what is going wrong on your dataset without debugging the code. But it could be either 1) you need to lower the learning rate. 2) or check if division by zero is happening anywhere. 3) Normalize the input time-series value to be zero mean and unit variance.

**Comment by deniz0158** [comment]
Hi, I am having kinda same issue as well, but with your data. Firstly, it gives me the following error:

new_pred_ = np.random.normal(loc=mu_[0][select_mixture], scale=sigma_[0][select_mixture])

  File "mtrand.pyx", line 1651, in mtrand.RandomState.normal

ValueError: scale < 0

and if I hard code the scale just to see what it does, the fake data list is filled with nan values. I havent tried a different data set yet. It is giving me the error on the data set given. Thanks in advance. :)
